name: eventhub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  firebase_core: any
  firebase_auth: any
  firebase_storage: any
  cloud_firestore: any
  intl: ^0.20.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/EventHUB_logo.png  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/EventHUB_logo.png"
  adaptive_icon_background: "#0B0F1A" 
  adaptive_icon_foreground: "assets/images/EventHUB_logo.png"