// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANsV03rfYRAxK63gC5zoAhL46W9ooX-js',
    appId: '1:51764376283:web:2a1a9de5f2d4cc03be12fe',
    messagingSenderId: '51764376283',
    projectId: 'eventhub-app-15f23',
    authDomain: 'eventhub-app-15f23.firebaseapp.com',
    storageBucket: 'eventhub-app-15f23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUoTJqKfAwn7kjrblo1BDY0D1avJAGZVk',
    appId: '1:51764376283:android:1b33a685c913dbacbe12fe',
    messagingSenderId: '51764376283',
    projectId: 'eventhub-app-15f23',
    storageBucket: 'eventhub-app-15f23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGFxZXp-d14FKxbo65s-azic_UJHxc9FA',
    appId: '1:51764376283:ios:159c920a2bec17bbbe12fe',
    messagingSenderId: '51764376283',
    projectId: 'eventhub-app-15f23',
    storageBucket: 'eventhub-app-15f23.firebasestorage.app',
    iosBundleId: 'com.example.eventhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGFxZXp-d14FKxbo65s-azic_UJHxc9FA',
    appId: '1:51764376283:ios:159c920a2bec17bbbe12fe',
    messagingSenderId: '51764376283',
    projectId: 'eventhub-app-15f23',
    storageBucket: 'eventhub-app-15f23.firebasestorage.app',
    iosBundleId: 'com.example.eventhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANsV03rfYRAxK63gC5zoAhL46W9ooX-js',
    appId: '1:51764376283:web:e244752020ce3ca3be12fe',
    messagingSenderId: '51764376283',
    projectId: 'eventhub-app-15f23',
    authDomain: 'eventhub-app-15f23.firebaseapp.com',
    storageBucket: 'eventhub-app-15f23.firebasestorage.app',
  );
}
